import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";
import { authTables } from "@convex-dev/auth/server";

export default defineSchema({
  ...authTables,
  profiles: defineTable({ userId: v.id("users"), name: v.string(), role: v.string(), organization: v.optional(v.string()), permissions: v.optional(v.array(v.string())) }).index("by_user", ["userId"]).index("by_role", ["role"]),
  records: defineTable({ kind: v.string(), title: v.string(), status: v.string(), version: v.number(), ownerId: v.id("users"), memberIds: v.array(v.id("users")), data: v.any(), createdAt: v.number(), updatedAt: v.number() }).index("by_kind", ["kind"]).index("by_owner_kind", ["ownerId", "kind"]).index("by_status", ["status"]).index("by_kind_pilot", ["kind", "data.pilotId"]).index("by_kind_offer", ["kind", "data.offerId"]).index("by_kind_card", ["kind", "data.cardId"]).index("by_kind_thread", ["kind", "data.threadId"]).index("by_kind_call", ["kind", "data.callId"]).index("by_kind_innovation", ["kind", "data.innovationId"]).index("by_kind_created", ["kind", "createdAt"]).index("by_kind_validity", ["kind", "data.validUntil"]),
  recordAccess: defineTable({ userId: v.id("users"), recordId: v.id("records"), kind: v.string() }).index("by_user_kind", ["userId", "kind"]).index("by_record", ["recordId"]),
  knowledgeChunks: defineTable({ knowledgeId: v.id("knowledge"), stableId: v.string(), version: v.number(), ordinal: v.number(), locator: v.string(), text: v.string(), hash: v.string(), sourceIds: v.array(v.id("sources")), embedding: v.optional(v.array(v.float64())), embeddingModel: v.optional(v.string()), searchText: v.string(), retrievalScope: v.string(), publishedScope: v.string() }).index("by_knowledge", ["knowledgeId"]).index("by_stable_hash", ["stableId", "hash"]).searchIndex("by_text", { searchField: "searchText", filterFields: ["retrievalScope"] }).vectorIndex("by_embedding", { vectorField: "embedding", dimensions: 1536, filterFields: ["retrievalScope"] }),
  revisions: defineTable({ recordId: v.id("records"), version: v.number(), data: v.any(), title: v.string(), status: v.string(), actorId: v.id("users"), createdAt: v.number() }).index("by_record", ["recordId"]),
  sources: defineTable({ title: v.string(), url: v.string(), publisher: v.string(), retrievedAt: v.number(), publishedAt: v.optional(v.number()), geography: v.string(), period: v.optional(v.string()), rights: v.string(), reviewAt: v.number(), hash: v.string(), version: v.number(), status: v.string(), demo: v.boolean(), locator: v.optional(v.string()), body: v.optional(v.string()) }).index("by_url", ["url"]).index("by_status", ["status"]),
  knowledge: defineTable({ stableId: v.string(), version: v.number(), status: v.string(), kind: v.string(), title: v.string(), summary: v.string(), body: v.string(), tags: v.array(v.string()), problemTags: v.array(v.string()), audienceTags: v.array(v.string()), sourceIds: v.array(v.id("sources")), requirements: v.array(v.any()), evidenceLevel: v.string(), demo: v.boolean(), searchText: v.string(), embedding: v.optional(v.array(v.float64())), embeddingPublished: v.optional(v.boolean()), publishedScope: v.string(), retrievalScope: v.optional(v.string()), createdAt: v.optional(v.number()), updatedAt: v.optional(v.number()), ownerId: v.optional(v.id("users")), reviewedBy: v.optional(v.id("users")), metadata: v.optional(v.any()) }).index("by_stable", ["stableId"]).index("by_owner", ["ownerId"]).index("by_kind", ["kind"]).index("by_status", ["status"]).index("by_scope_kind", ["publishedScope", "kind"]).searchIndex("search_knowledge", { searchField: "searchText", filterFields: ["publishedScope", "kind", "retrievalScope"] }).vectorIndex("by_embedding", { vectorField: "embedding", dimensions: 1536, filterFields: ["publishedScope", "retrievalScope"] }),
  matches: defineTable({ needId: v.optional(v.id("records")), ownerId: v.optional(v.id("users")), needVersion: v.number(), corpusVersion: v.number(), matchRevision: v.optional(v.number()), result: v.any(), createdAt: v.number() }).index("by_need", ["needId"]).index("by_owner", ["ownerId"]),
  notifications: defineTable({ userId: v.id("users"), title: v.string(), body: v.string(), recordId: v.optional(v.id("records")), key: v.string(), readAt: v.optional(v.number()), createdAt: v.number() }).index("by_user", ["userId"]).index("by_key", ["key"]),
  outbox: defineTable({ key: v.string(), kind: v.string(), payload: v.any(), status: v.string(), createdAt: v.number() }).index("by_key", ["key"]).index("by_status", ["status"]),
  jobs: defineTable({ kind: v.string(), status: v.string(), attempts: v.number(), payload: v.any(), error: v.optional(v.string()), createdAt: v.number(), updatedAt: v.number() }).index("by_status", ["status"]),
  audit: defineTable({ actorId: v.optional(v.id("users")), action: v.string(), entityId: v.string(), details: v.any(), createdAt: v.number() }).index("by_entity", ["entityId"]),
  aiUsage: defineTable({ userId: v.optional(v.id("users")), sessionId: v.optional(v.string()), operation: v.string(), model: v.string(), inputTokens: v.number(), outputTokens: v.number(), costUsd: v.number(), createdAt: v.number() }).index("by_created", ["createdAt"]).index("by_user", ["userId"]),
  meta: defineTable({ key: v.string(), value: v.any() }).index("by_key", ["key"]),
  files: defineTable({ ownerId: v.id("users"), recordId: v.id("records"), storageId: v.id("_storage"), name: v.string(), mimeType: v.string(), size: v.number(), status: v.string(), scan: v.string(), createdAt: v.number() }).index("by_record", ["recordId"]).index("by_storage", ["storageId"]),
});


