import {describe,it,expect,vi,afterEach} from 'vitest';
import {providerRequest,interpret,explain,embed} from '../convex/ai';
afterEach(()=>{vi.unstubAllGlobals();vi.unstubAllEnvs();});
const completion=(value:any)=>new Response(JSON.stringify({choices:[{message:{content:JSON.stringify(value)}}],usage:{prompt_tokens:20,completion_tokens:10}}),{status:200});
describe('Awaria modeli i walidacja wyniku',()=>{
 it('retries 429 once and accepts successful second answer',async()=>{const fetch=vi.fn().mockResolvedValueOnce(new Response('',{status:429})).mockResolvedValueOnce(new Response('{"ok":true}',{status:200}));vi.stubGlobal('fetch',fetch);expect(await providerRequest('https://example.invalid','fake-key',{})).toEqual({ok:true});expect(fetch).toHaveBeenCalledTimes(2);});
 it('does not loop or expose error response after permanent denial',async()=>{const fetch=vi.fn().mockResolvedValue(new Response('sensitive-provider-detail',{status:401}));vi.stubGlobal('fetch',fetch);await expect(providerRequest('https://example.invalid','fake-key',{})).rejects.toThrow('HTTP 401');expect(fetch).toHaveBeenCalledTimes(1);});
 it('bounds network retry and returns usable timeout message',async()=>{const fetch=vi.fn().mockRejectedValue(new DOMException('network internals','TimeoutError'));vi.stubGlobal('fetch',fetch);await expect(providerRequest('https://example.invalid','fake-key',{})).rejects.toThrow('Przekroczono czas');expect(fetch).toHaveBeenCalledTimes(2);});
 it('rejects malformed structured interpretation',async()=>{vi.stubEnv('GROQ_API_KEY','test');vi.stubGlobal('fetch',vi.fn().mockResolvedValue(completion({problem:42})));await expect(interpret('Potrzeba rozmów i kontaktów społecznych')).rejects.toThrow('Niepoprawna interpretacja');});
 it('never forwards email and phone to model',async()=>{vi.stubEnv('GROQ_API_KEY','test');const fetch=vi.fn().mockResolvedValue(completion({problem:'Potrzeba',outcome:'Kontakt',audience:'Seniorzy',context:'',constraints:[],unknowns:[]}));vi.stubGlobal('fetch',fetch);await interpret('Seniorzy potrzebują kontaktu. Kontakt abc@example.pl +48 123 456 789');const body=fetch.mock.calls[0][1].body;expect(body).not.toContain('abc@example.pl');expect(body).not.toContain('123 456 789');});
 it('rejects invented IDs, versions and source identifiers from explanations',async()=>{vi.stubEnv('GROQ_API_KEY','test');vi.stubGlobal('fetch',vi.fn().mockResolvedValue(completion({explanations:[{id:'real',version:1,why:'Poparte źródłem',sourceIds:['source']},{id:'invented',version:1,why:'Nieznane',sourceIds:['source']},{id:'real',version:2,why:'Inna wersja',sourceIds:['source']},{id:'real',version:1,why:'Inne źródło',sourceIds:['fabricated']}]})));const result=await explain('Opis potrzeby',[{id:'real',version:1,title:'Tytuł',summary:'Opis',demo:true,conditions:[],sources:[{id:'source'}]}]);expect(result.value.explanations).toHaveLength(1);expect(result.value.explanations[0].why).toBe('Poparte źródłem');});
 it('rejects embedding dimensions incompatible with index',async()=>{vi.stubEnv('OPENAI_API_KEY','test');vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(JSON.stringify({data:[{index:0,embedding:[0.1,0.2]}],usage:{total_tokens:2}}),{status:200})));await expect(embed(['opis'])).rejects.toThrow('wymiar embeddingu');});
 it('accepts only actual fragment IDs in a grounded explanation',async()=>{vi.stubEnv('GROQ_API_KEY','test');vi.stubGlobal('fetch',vi.fn().mockResolvedValue(completion({explanations:[{id:'real',version:1,why:'Prawidłowa strona',sourceIds:['source'],fragmentIds:['fragment-1']},{id:'real',version:1,why:'Zmyślona strona',sourceIds:['source'],fragmentIds:['invented']},{id:'real',version:1,why:'Brak podstawy',sourceIds:['source'],fragmentIds:[]}]})));const result=await explain('Opis potrzeby',[{id:'real',version:1,title:'Tytuł',summary:'Opis',demo:true,conditions:[],sources:[{id:'source'}],fragments:[{id:'fragment-1',locator:'strona 2, fragment 1',text:'Opis rzeczywistej podstawy',sourceIds:['source']}]}]);expect(result.value.explanations).toHaveLength(1);expect(result.value.explanations[0].fragmentIds).toEqual(['fragment-1']);});
});
