import {describe,expect,it} from 'vitest';
import {describeMaterialChange} from '../domain/matching';
const item={id:'card',stableId:'card',title:'Kręgi sąsiedzkie',version:1,evidenceLevel:'concept',conditions:[{key:'room',label:'Dostępna sala',status:'unknown',evidence:'Brak potwierdzenia.'}],sources:[{id:'source',title:'Opis źródłowy',url:'/sources/demo-corpus.html',version:1}]};
describe('Konkretna różnica obserwowanej potrzeby',()=>{
 it('names new and removed proposals and retains a source link',()=>{const change=describeMaterialChange({innovations:[],information:[]},{innovations:[item],information:[]})!;expect(change.message).toContain('Kręgi sąsiedzkie');expect(change.entries[0].sources[0].url).toBe('/sources/demo-corpus.html');const removed=describeMaterialChange({innovations:[item]},{innovations:[]})!;expect(removed.message).toContain('nie jest już rekomendowane');});
 it('explains exact condition and evidence changes instead of a generic new-knowledge message',()=>{const after={...item,conditions:[{key:'room',label:'Dostępna sala',status:'unmet',evidence:'Deklaracja instytucji: false.'}]};const change=describeMaterialChange({innovations:[item]},{innovations:[after]})!;expect(change.type).toBe('condition_changed');expect(change.message).toContain('Dostępna sala: niepotwierdzony → niespełniony');expect(change.message).toContain('Deklaracja instytucji: false');});
 it('reports source version change and ignores unchanged repeated results',()=>{expect(describeMaterialChange({innovations:[item]},{innovations:[item]})).toBeNull();const change=describeMaterialChange({innovations:[item]},{innovations:[{...item,version:2}]})!;expect(change.message).toContain('1 → 2');});
 it('names a changed threshold even while both declarations remain unknown',()=>{const before={...item,conditions:[{...item.conditions[0],expected:2,sourceVersion:1}]};const after={...item,conditions:[{...item.conditions[0],expected:4,sourceVersion:2}]};const change=describeMaterialChange({innovations:[before]},{innovations:[after]})!;expect(change.type).toBe('condition_changed');expect(change.message).toContain('Wymagana wartość: 2 → 4');expect(change.message).toContain('wersja 1 → 2');});
 it('does not notify only because an older result lacked newly added schema fields',()=>{const after={...item,conditions:[{...item.conditions[0],expected:true,operator:'eq',unit:null}]};expect(describeMaterialChange({innovations:[item]},{innovations:[after]})).toBeNull();});
 it('names removed conditions rather than creating an empty message',()=>{const change=describeMaterialChange({innovations:[item]},{innovations:[{...item,conditions:[]}]})!;expect(change.message).toContain('Usunięto warunek „Dostępna sala”');});
});
