/** Authored synthetic demonstration records, never represented as ROPS evidence. */
import type {Requirement} from './matching';
const reviewAt=Date.UTC(2027,9,3);
const condition=(id:string,key:string,label:string,expected:any=true,extra:Partial<Requirement>={}):Requirement=>({id,key,label,expected,category:'resources',operator:typeof expected==='number'?'gte':'eq',mandatory:true,allowPartner:true,approved:true,sourceVersion:1,responsible:'Kurator demonstracyjny',reviewAt,...extra});
export const corpusSources=[{stableId:'splot-demo-corpus-v1',title:'Splot: autorski korpus demonstracyjny, wersja 1',url:'/sources/demo-corpus.html',version:1,demo:true,license:'CC BY 4.0',status:'published',publisher:'Zespół Splot',description:'Syntetyczne opisy do sprawdzenia przepływów. Nie są innowacjami ani badaniami ROPS.'}];
const entries=[
 ['sasiedzi','Kręgi sąsiedzkie','Stałe małe grupy spotkań i telefonów przeciwdziałające samotności seniorów.', ['samotnosc'],['seniorzy'],[condition('coordinator','coordinator','Koordynator spotkań'),condition('room','accessibleRoom','Dostępna sala na spotkania')]],
 ['telefon','Rozmowa po sąsiedzku','Regularne rozmowy telefoniczne z przygotowanymi wolontariuszami dla osób samotnych i pozostających w domu.', ['samotnosc'],['seniorzy'],[condition('volunteer','volunteers','Dwóch przeszkolonych wolontariuszy',2),condition('consent','participantConsent','Zgoda uczestników na kontakt')]],
 ['mobilnosc','Przejazd do usług','Koordynacja wspólnych dojazdów osób z ograniczoną mobilnością do usług społecznych i spotkań.', ['transport'],['seniorzy','dostepnosc'],[condition('vehicle','accessibleVehicle','Dostępny pojazd z uprawnionym kierowcą'),condition('coordinator','coordinator','Koordynator przejazdów')]],
 ['cyfrowy','Spokojny krok cyfrowy','Ćwiczenie samodzielnej obsługi smartfonu, bankomatu i internetu przez seniorów w bezpiecznych scenariuszach.', ['cyfrowe'],['seniorzy'],[condition('trainer','digitalTrainer','Instruktor kompetencji cyfrowych'),condition('devices','devices','Urządzenia do ćwiczeń',2)]],
 ['cyfrowy-dom','Cyfrowe wizyty domowe','Indywidualne ćwiczenia korzystania z telefonu i usług internetowych w domu osoby starszej.', ['cyfrowe'],['seniorzy'],[condition('volunteer','volunteers','Przeszkolony wolontariusz',1),condition('consent','participantConsent','Zgoda uczestnika na wizytę')]],
 ['wytchnienie','Godzina wytchnienia','Planowane krótkie zastępstwo opiekuńcze oraz grupa wsparcia dla rodzin opiekujących się osobą zależną.', ['opieka'],['rodziny'],[condition('care','qualifiedCarer','Osoba z wymaganymi kompetencjami opiekuńczymi'),condition('budget','budgetGrosz','Środki na demonstracyjny mikrotest',50000,{category:'budget',unit:'gr'})]],
 ['emocje','Przystań młodych','Moderowane spotkania rówieśnicze o emocjach, stresie i szukaniu pomocy, z opieką specjalisty. To nie jest leczenie ani pomoc kryzysowa.', ['psychiczne'],['mlodziez'],[condition('psychologist','psychologist','Psycholog nadzorujący program'),condition('room','accessibleRoom','Dostępna sala')]],
 ['praca','Most do zatrudnienia','Towarzyszenie osobom długo pozostającym bez pracy w rozpoznaniu kompetencji, kontakcie z pracodawcami i próbie zawodowej.', ['praca'],['dorosli'],[condition('mentor','jobMentor','Mentor aktywizacji zawodowej'),condition('employers','employerPartners','Potwierdzeni partnerzy pracodawcy',1)]],
 ['dostepny','Urząd bez barier','Wspólne testowanie dostępności wizyty w urzędzie z osobami z niepełnosprawnością oraz wdrażanie prostych usprawnień.', ['dostepnosc'],['dostepnosc'],[condition('expert','accessibilityExpert','Ekspert dostępności'),condition('decision','institutionApproval','Zgoda instytucji na zmiany')]],
 ['integracja','Sąsiedzki tandem językowy','Pary nowych i dotychczasowych mieszkańców ćwiczą język polski i wspólnie poznają lokalne usługi.', ['integracja'],['migranci'],[condition('volunteers','volunteers','Przygotowani wolontariusze',2),condition('coordinator','coordinator','Koordynator spotkań')]],
 ['zywnosc','Wspólny stół','Lokalna sieć bezpiecznego przekazywania nadwyżek żywności i wspólnych posiłków dla osób w trudnej sytuacji.', ['zywnosc'],['mieszkancy'],[condition('food','foodSafety','Zweryfikowane warunki bezpieczeństwa żywności'),condition('location','foodStorage','Odpowiednie miejsce przechowywania żywności')]],
 ['mieszkanie','Krok do mieszkania','Koordynacja wsparcia mieszkaniowego dla osób zagrożonych utratą lokum, z asystentem i lokalnymi partnerami.', ['mieszkanie'],['dorosli'],[condition('housing','housingAssistant','Asystent mieszkaniowy'),condition('partners','housingPartners','Potwierdzeni partnerzy mieszkaniowi',1)]],
] as const;
export const demoCorpus=entries.map(([stableId,title,summary,problemTags,audienceTags,requirements])=>({stableId,version:1,kind:'innovation',status:'published',title,summary,body:`${summary} Scenariusz autorski, syntetyczny. Warunki i kwoty są założeniami do demonstracji, bez potwierdzonej skuteczności społecznej. Przed rzeczywistym użyciem wymaga oceny eksperta i dostosowania do lokalnych przepisów.`,tags:[...problemTags,...audienceTags],problemTags:[...problemTags],audienceTags:[...audienceTags],sourceIds:[],requirements:[...requirements],evidenceLevel:'concept',demo:true,publishedScope:'public:published',retrievalScope:'public:published:innovation'}));
for(const topic of ['samotnosc','transport','cyfrowe','opieka','psychiczne','praca','dostepnosc','integracja','zywnosc','mieszkanie']){
  const base=demoCorpus.find(item=>(item.problemTags as string[]).includes(topic))!;
  (demoCorpus as any[]).push({stableId:`guide-${topic}`,version:1,kind:'report',status:'published',title:`Przewodnik: ${base.title.toLowerCase()}`,summary:`Pytania do diagnozy potrzeb, dostępne zasoby i plan pomiaru w obszarze: ${topic}. Materiał demonstracyjny.`,body:`${base.summary} Przy diagnozie zapytaj uczestników o oczekiwany efekt. Zmierz sytuację przed testem i po nim. Zbierz rezygnacje i niepożądane skutki. Nie przypisuj zmiany samemu testowi bez porównania. Dane oraz opis są fikcyjne, nie pochodzą z raportu ROPS.`,tags:[topic],problemTags:[topic],audienceTags:base.audienceTags,sourceIds:[],requirements:[],evidenceLevel:'concept',demo:true,publishedScope:'public:published',retrievalScope:'public:published:information'});
}
