import { readFile,writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
const read=async name=>JSON.parse(await readFile(`artifacts/${name}.json`,'utf8'));
const [deployment,domain,browser,library,restore,load]=await Promise.all(['deployment','domain-tests','playwright-results','library-media-live','restore-verification','matching-load'].map(read));
const [publicRun,ux]=await Promise.all(['public-e2e-run','ux-audit-final'].map(read));
assert.equal(publicRun.url,deployment.url);
assert.equal(publicRun.beforeBuild,deployment.build);assert.equal(publicRun.afterBuild,deployment.build);
assert.equal(publicRun.exitCode,0);
assert(Date.parse(publicRun.startedAt)>=Date.parse(deployment.publishedAt));
assert.equal(publicRun.browserReportSha256,createHash('sha256').update(await readFile('artifacts/playwright-results.json')).digest('hex'));
assert.equal(domain.numFailedTests,0);assert(domain.numPassedTests>0);
assert.equal(domain.success,true);assert.equal(browser.errors?.length || 0,0);
assert.equal(browser.stats.unexpected,0);assert.equal(browser.stats.skipped,0);assert(browser.stats.expected>=6);
assert(restore.businessTableCountsAgree && restore.restoredFileHashAgrees && restore.recoveredForeignFileDenied && restore.restoredBrowserLogin==='passed');
assert.equal(library.browserErrors.length,0);assert(library.accessibility.every(row=>!row.violations.some(v=>['critical','serious'].includes(v.impact))));
assert.equal(load.fixtureAdded,10000);assert.equal(load.fixtureRemoved,10000);assert.equal(load.fixtureRemaining,false);
const performance=load.results.map(({scenario,p95Ms,success,sessions,tasks})=>({scenario,p95Ms,success,total:sessions||tasks,targetMs:tasks?10000:2000,targetMet:p95Ms<=(tasks?10000:2000)}));
const report={verifiedAt:new Date().toISOString(),deployment,team:JSON.parse(await readFile('TEAM.json','utf8')),runtime:process.version,domain:{passed:domain.numPassedTests,failed:domain.numFailedTests},browser:{passed:browser.stats.expected,failed:browser.stats.unexpected,skipped:browser.stats.skipped,durationMs:browser.stats.duration},library:{videoPlayback:true,captions:true,rangeRequests:true,courseSteps:library.courseSteps,mapPoints:library.indicators,seriousOrCriticalAxe:0},restore:{independentDeployment:restore.restoredDeployment,browserLogin:restore.restoredBrowserLogin,countsAgree:restore.businessTableCountsAgree,privateFileHashAndAcl:true,durationSeconds:restore.durationSeconds},performance,externalAcceptance:['Ocena merytoryczna ROPS na zatwierdzonym korpusie.','Badanie z co najmniej pięcioma odbiorcami i ręczna ocena NVDA/VoiceOver.','Kontrakt rzeczywistego systemu grantowego i konfiguracja tożsamości produkcyjnej.'],submissionSent:false};
report.browserRun={startedAt:publicRun.startedAt,completedAt:publicRun.completedAt,beforeBuild:publicRun.beforeBuild,afterBuild:publicRun.afterBuild};
report.ux={status:ux.status,reason:ux.reason,findings:ux.findings?.length??0,report:'artifacts/ux-audit-final.json',environment:'Historical independent audit of the previous release, on an isolated preview. Current pitch changes and the two follow-up corrections are covered by tests/e2e/pitch-product.spec.ts in the public regression run; this does not constitute a new independent UX audit.'};
await writeFile('artifacts/browser-verification.json',JSON.stringify({testedAt:publicRun.completedAt,publicUrl:deployment.url,build:deployment.build,...report.browser,...report.browserRun},null,2));
await writeFile('artifacts/release-verification.json',JSON.stringify(report,null,2));
console.log(JSON.stringify(report,null,2));
