import { useRef, useState } from 'react';
import { useAction, useConvex, useMutation, usePaginatedQuery, useQuery } from 'convex/react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { api } from '../convex/_generated/api';
import { ArrowDown, ArrowRight, ArrowUpRight, BookOpen, Check, ChevronRight, CircleHelp, Clock3, FileText, FlaskConical, Heart, HeartHandshake, Leaf, Lightbulb, List, MapPin, Search, ShieldCheck, SlidersHorizontal, Sparkles, Sprout, Users } from 'lucide-react';
import { useApp } from './context';
import { Badge, Button, Checkbox, Empty, Input, Loading, Modal, Notice, PageHeading, Select, Stepper, Textarea, errorText, useDraft } from './ui';
import { RegionalMap } from './RegionalMap';
import { readableDemoTitle } from './display-labels';
import { DemoTitleDetails } from './DemoTitleDetails';
const endpoint: any = api;
const themes = [{ key: 'samotnosc', label: 'Relacje i samotność', icon: Heart, tone: 'rose' }, { key: 'cyfrowe', label: 'Kompetencje cyfrowe', icon: Lightbulb, tone: 'sand' }, { key: 'dostepnosc', label: 'Dostępność', icon: Users, tone: 'blue' }, { key: 'opieka', label: 'Wsparcie i opieka', icon: HeartHandshake, tone: 'mint' }];
function Artwork({ type = 0 }: { type?: number }) { return <div className={`artwork artwork-${type % 4}`} aria-hidden="true"><div className="art-orbit" /><div className="art-plant"><i /><i /><i /><i /></div><div className="art-person p1"><i /><b /></div><div className="art-person p2"><i /><b /></div><div className="art-person p3"><i /><b /></div><span className="art-sun" /><span className="art-ground" /></div>; }
export function HomePage() {
  const { user, navigate, requireAuth } = useApp();
  const knowledge = useQuery(endpoint.knowledge.list, {});
  const [description, setDescription] = useState('');
  function search(text = description) { localStorage.setItem('splot:search', JSON.stringify({ description: text, audience: '', municipality: '' })); navigate('search'); }
  return <><div className="welcome-line"><span><span className="status-dot" /> SPLOT DLA HUBMI</span><span>Innowacje społeczne w praktyce</span></div><section className="hero"><div className="hero-content"><span className="eyebrow">DLA MIESZKAŃCÓW, NGO I INSTYTUCJI</span><h1>Znajdź rozwiązanie.<br />Zaplanuj <span>wdrożenie.</span></h1><p>Opisz potrzebę. Porównaj propozycje ze źródłami, sprawdź wymagania i zaproś partnerów do wspólnego testu.</p><label className="hero-search-label" htmlFor="home-need">Opisz, czego potrzebujesz</label><form className="hero-search" onSubmit={e => { e.preventDefault(); search(); }}><Search size={23} /><input id="home-need" aria-describedby="home-search-hint" placeholder="Np. spotkań dla seniorów" value={description} onChange={e => setDescription(e.target.value)} /><button type="submit" aria-label="Znajdź rozwiązanie"><ArrowRight size={23} /></button></form><div id="home-search-hint" className="hero-hint"><ShieldCheck size={15} /> Wyszukaj bez konta. Zapisz plan, gdy wybierzesz rozwiązanie.</div></div><div className="hero-visual" aria-hidden="true"><div className="hero-ring ring-one" /><div className="hero-ring ring-two" /><div className="hero-ring ring-three" /><div className="hero-center"><span className="brand-mark"><span /><span /><span /><span /></span></div><span className="float-label fl-one"><Heart size={19} /> Potrzeba</span><span className="float-label fl-two"><Lightbulb size={19} /> Pomysł</span><span className="float-label fl-three"><Users size={19} /> Współpraca</span><span className="hero-dot hd-one" /><span className="hero-dot hd-two" /><span className="hero-leaf" /></div></section>
    <section className="entry-grid" aria-label="Wybierz swoją ścieżkę"><button onClick={() => navigate('search')} className="entry-card"><span className="entry-icon mint"><Search size={24} /></span><h2>Szukam rozwiązania</h2><p>Opisz potrzebę. Poznaj innowacje, które mogą pomóc.</p><span className="entry-link">Porównaj rozwiązania <ArrowRight size={18} /></span></button><button onClick={() => { if (requireAuth()) navigate('idea', 'new'); }} className="entry-card"><span className="entry-icon sand"><Lightbulb size={24} /></span><h2>Mam pomysł</h2><p>Zapisz fiszkę, ułóż plan w Canwie i przygotuj wniosek.</p><span className="entry-link">Rozwiń swój pomysł <ArrowRight size={18} /></span></button><button onClick={() => navigate('pilots')} className="entry-card"><span className="entry-icon rose"><HeartHandshake size={24} /></span><h2>Chcę pomóc lub testować</h2><p>Dołącz do pilotażu i pokaż, co warto poprawić w usłudze.</p><span className="entry-link">Zobacz otwarte testy <ArrowRight size={18} /></span></button></section>
    <section className="section-block"><div className="section-heading"><div><span className="eyebrow">BIBLIOTEKA INNOWACJI</span><h2>Poznaj dostępne rozwiązania</h2></div><button className="text-button" onClick={() => navigate('library')}>Cała biblioteka <ArrowUpRight size={18} /></button></div><div className="innovation-grid">{knowledge === undefined ? <Loading /> : knowledge.filter((k: any) => k.kind === 'innovation').slice(0, 3).map((item: any, index: number) => <article className="innovation-card" key={item._id}><button className="art-button" aria-label={`Poznaj: ${readableDemoTitle(item.title).title}`} onClick={() => navigate('innovation', item._id)}><Artwork type={index} /></button><div className="innovation-body"><div className="card-meta"><Badge>{themes.find(t => item.problemTags?.includes(t.key) || item.tags?.includes(t.key))?.label || 'Innowacja społeczna'}</Badge><span className="subtle">Koncepcja</span></div><h3><button onClick={() => navigate('innovation', item._id)}>{readableDemoTitle(item.title).title}</button></h3><DemoTitleDetails title={item.title} /><p>{item.summary}</p><button className="text-button" onClick={() => navigate('innovation', item._id)}>Poznaj rozwiązanie <ArrowRight size={17} /></button></div></article>)}</div></section>
    <section className="topic-section"><div><span className="eyebrow">WYBIERZ TEMAT</span><h2>Jakiego wsparcia szukasz?</h2></div><div className="topic-chips">{themes.map(({ label, icon: Icon, tone }) => <button key={label} onClick={() => search(label)}><span className={`topic-icon ${tone}`}><Icon size={18} /></span>{label}<ChevronRight size={16} /></button>)}</div></section><section className="journey"><span className="journey-icon"><Sprout size={30} /></span><div><h2>Przygotuj plan i ustal, kto pomoże go zrealizować.</h2><p>Zapisz potrzebę, znajdź partnerów, przygotuj plan i sprawdź, co działa.</p></div><Button secondary onClick={() => user ? navigate('cases') : requireAuth()}>Otwórz moje sprawy <ArrowRight size={17} /></Button></section></>;
}
const searchSchema = z.object({ description: z.string().min(12, 'Opisz potrzebę w co najmniej 12 znakach.').max(5000, 'Skróć opis do 5000 znaków.'), audience: z.string(), municipality: z.string() });
export function SearchPage() {
  const { user, navigate, requireAuth, toast } = useApp();
  const [draft, setDraft] = useDraft('search', { description: '', audience: '', municipality: '' });
  const [resources, setResources] = useState<Record<string, any>>({});
  const [result, setResult] = useState<any>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [watch, setWatch] = useState(true);
  const [assisted, setAssisted] = useState(false);
  const [authorEmail, setAuthorEmail] = useState('');
  const createAssisted = useMutation(endpoint.assistance.create);
  const [more, setMore] = useState(false);
  const [compare, setCompare] = useState<string[]>([]);
  const [comparison, setComparison] = useState(false);
  const [saved, setSaved] = useState<string>();
  const [skipQuestion, setSkipQuestion] = useState(false);
  const match = useAction(endpoint.matching.match);
  const convex = useConvex(); const searchRevision = useRef(0);
  const save = useMutation(endpoint.hub.save);
  const form = useForm({ resolver: zodResolver(searchSchema), defaultValues: draft });
  async function search(values: typeof draft, res = resources) {
    const revision = ++searchRevision.current; setBusy(true); setError(''); setDraft(values); setSkipQuestion(false);
    try { const preview = await convex.query(endpoint.matching.preview, { description: values.description, audience: values.audience, resources: res }); if (revision === searchRevision.current) setResult(preview); } catch { /* The full search remains available if the quick preview fails. */ }
    try { let sessionId = sessionStorage.getItem('splot:session'); if (!sessionId) { sessionId = crypto.randomUUID(); sessionStorage.setItem('splot:session', sessionId); } const response = await match({ ...values, resources: res, sessionId }); if (revision === searchRevision.current) setResult(response); }
    catch (e) { if (revision === searchRevision.current) setError(errorText(e)); } finally { if (revision === searchRevision.current) setBusy(false); }
  }
  async function saveNeed() { if (!requireAuth()) return; try { if (assisted) { await createAssisted({ authorEmail, description:draft.description, group:draft.audience, municipality:draft.municipality }); toast('Zapisano zgłoszenie z pomocą ROPS. Autor otrzymał prośbę o potwierdzenie treści.'); navigate('cases'); return; } const id = await save({ kind: 'need', ...(saved ? { id: saved } : {}), title: draft.description.slice(0, 90), data: { description: draft.description, group: draft.audience, municipality: draft.municipality, resources, watch, interpretation: result?.interpretation, matchResult: result, nextStep: 'Wybierz innowację albo umów konsultację' } }); setSaved(id); toast('Zapisano potrzebę. Znajdziesz ją w Moich sprawach.'); } catch (e) { toast(errorText(e), true); } }
  async function createCard(item: any) { if (!requireAuth()) return; if (assisted) { toast('Najpierw zapisz zgłoszenie i zaczekaj na potwierdzenie autora.', true); return; } try { const needId = saved || await save({ kind: 'need', title: draft.description.slice(0, 90), data: { description: draft.description, group: draft.audience, municipality: draft.municipality, resources, watch, matchResult: result } }); setSaved(needId); const id = await save({ kind: 'card', title: `${item.title}: plan wdrożenia`, data: { needId, innovationId: item.id, innovationVersion: item.version, sourceIds: item.sources.map((s: any) => s.id), goal: result.interpretation.outcome, audience: draft.audience || result.interpretation.audience, mechanism: item.summary, resources, requirements: item.conditions, budgetItems: [], metrics: '', risks: '', accessibility: '', timeline: '', adaptations: '', provenance: 'Źródło demonstracyjne; lokalne pola są deklaracją autora.' } }); navigate('card', id); } catch (e) { toast(errorText(e), true); } }
  const shown = result?.innovations?.slice(0, more ? undefined : 3) || [];
  return <><PageHeading eyebrow="DOPASOWANIE ROZWIĄZAŃ" title="Znajdź rozwiązanie dla swojej społeczności" description="Opisz sytuację własnymi słowami. Pokażemy źródła, warunki i możliwe kolejne kroki." /><Stepper steps={['Twoja potrzeba', 'Możliwe rozwiązania', 'Wspólny plan']} active={result ? 1 : 0} /><div className={`search-layout ${result ? 'has-results' : ''}`}><section className="panel search-form"><div className="panel-title"><span className="entry-icon mint"><Search size={21} /></span><h2>Co chcesz zmienić?</h2></div><form onSubmit={form.handleSubmit(v => search(v))} className="stack"><div className="field"><label htmlFor="need-description">Opisz swoją potrzebę <span aria-hidden="true">*</span></label><textarea id="need-description" rows={5} placeholder="Np. starsi mieszkańcy naszej gminy rzadko wychodzą z domu. Chcielibyśmy pomóc im odbudować relacje z sąsiadami…" {...form.register('description', { onChange: e => setDraft({ ...draft, description: e.target.value }) })} aria-invalid={!!form.formState.errors.description} aria-describedby={`need-description-hint${form.formState.errors.description ? ' need-description-error' : ''}`} /><small id="need-description-hint" className="field-hint">Nie podawaj danych osobowych ani szczegółów zdrowotnych.</small>{form.formState.errors.description && <small id="need-description-error" role="alert" className="field-error">{form.formState.errors.description.message}</small>}</div><div className="two-columns"><div className="field"><label htmlFor="need-audience">Dla kogo? <span className="optional">opcjonalnie</span></label><input id="need-audience" placeholder="Np. seniorzy" {...form.register('audience')} /></div><div className="field"><label htmlFor="need-place">Gmina lub miejscowość <span className="optional">opcjonalnie</span></label><input id="need-place" placeholder="Np. Skawina" {...form.register('municipality')} /></div></div>{error && <Notice error>{error}</Notice>}<Button type="submit" loading={busy}><Sparkles size={18} />{busy ? 'Szukamy w opublikowanej wiedzy…' : 'Znajdź pasujące rozwiązania'}<ArrowRight size={18} /></Button><p className="form-note">Opis pozostaje prywatny. Zapiszesz go na koncie dopiero na własne życzenie.</p></form></section>
      {!result && <aside className="search-explainer"><span className="eyebrow">JAK DZIAŁA WYSZUKIWANIE</span><h2>Zacznij od opisu sytuacji.</h2><p>Napisz, kogo dotyczy problem i jaki efekt chcesz osiągnąć.</p><ul className="icon-list"><li><BookOpen size={21} /><span><strong>Wiedza z podanym źródłem</strong>Innowacje i materiały informacyjne osobno.</span></li><li><CircleHelp size={21} /><span><strong>Pytanie, które ma znaczenie</strong>Dopytamy tylko o warunek zmieniający decyzję.</span></li><li><HeartHandshake size={21} /><span><strong>Konkretny następny krok</strong>Plan wdrożenia, partnerstwo lub rozmowa.</span></li></ul></aside>}
    </div>{result && <section className="search-results" aria-live="polite"><div className="interpretation panel"><div><Badge tone="good"><Check size={13} /> Tak rozumiemy Twoją potrzebę</Badge><h2>{result.interpretation.problem}</h2><p>{result.interpretation.outcome}</p><span className="subtle">Odbiorcy: {result.interpretation.audience || 'Do doprecyzowania'} · Kontekst: {result.interpretation.context || 'Opis użytkownika'}</span></div><details><summary>Popraw interpretację</summary><Textarea label="Oczekiwany efekt" value={result.interpretation.outcome} onChange={v => setResult({ ...result, interpretation: { ...result.interpretation, outcome: v } })} /><Button secondary small onClick={() => { const values = { ...form.getValues(), description: `${draft.description}\nOczekiwany efekt: ${result.interpretation.outcome}` }; form.setValue('description', values.description); void search(values); }}>Uwzględnij zmianę i wyszukaj ponownie</Button></details></div>
      {result.question && !skipQuestion && <div className="question-card"><span className="question-icon"><CircleHelp size={24} /></span><div><span className="eyebrow">JEDNO WAŻNE PYTANIE</span><h2>{result.question.text}</h2><p>{result.question.why}</p><div className="button-row">{result.question.options.map((option: any, index: number) => <Button secondary key={index} disabled={busy} onClick={() => { const updated = { ...resources, [result.question.field]: { value: option.value, confirmedAt: Date.now(), basis: 'declaration' } }; setResources(updated); void search(draft, updated); }}>{option.label}</Button>)}<button className="text-button" onClick={() => setSkipQuestion(true)}>Nie wiem / pomiń</button></div></div></div>}
      <div className="section-heading"><div><span className="eyebrow">INNOWACJE DO ROZWAŻENIA</span><h2>{result.abstention ? 'Jeszcze nie mamy potwierdzonego kierunku' : `${result.innovations.length} ${result.innovations.length === 1 ? 'możliwość' : 'możliwości'} dla Twojej potrzeby`}</h2></div>{compare.length > 1 && <Button secondary onClick={() => setComparison(true)}>Porównaj ({compare.length})</Button>}</div>{result.abstention && <Notice>{result.abstention} Możesz zapisać potrzebę, obserwować nową wiedzę lub skonsultować ją z ROPS.</Notice>}<div className="results-grid">{shown.map((item: any) => <article key={item.id} className="result-card"><div className="card-meta"><Badge tone={item.readiness === 'ready' ? 'good' : item.readiness === 'blocked' ? 'danger' : 'sand'}>{item.readiness === 'ready' ? 'Warunki zadeklarowane' : item.readiness === 'blocked' ? 'Jest bariera do rozwiązania' : 'Sprawdź warunki'}</Badge><Checkbox label="Porównaj" ariaLabel={`Porównaj: ${readableDemoTitle(item.title).title}`} checked={compare.includes(item.id)} onChange={v => setCompare(v ? [...compare, item.id] : compare.filter(id => id !== item.id))} /></div><h3>{readableDemoTitle(item.title).title}</h3><DemoTitleDetails title={item.title} /><p>{item.summary}</p><div className="reason"><strong>Dlaczego pasuje</strong><p>{item.why}</p></div><div className="requirements"><strong>Co trzeba zapewnić</strong>{item.conditions.map((c: any) => <div key={c.id} className={`condition ${c.status}`}><span>{c.status === 'met' ? <Check size={16} /> : c.status === 'unmet' ? '!' : '?'}</span><div>{c.label}<small>{c.status === 'met' ? 'Spełniony' : c.status === 'unmet' ? 'Niespełniony' : 'Nieznany'}{c.evidence ? ` · ${typeof c.evidence === 'string' ? c.evidence : 'deklaracja instytucji'}` : ''}</small></div></div>)}</div><div className="sources"><strong>Na czym oparto propozycję</strong>{item.sources.map((s: any) => <a href={s.url} target="_blank" rel="noreferrer" key={s.id}><FileText size={14} />{s.title}<ArrowUpRight size={13} /></a>)}<small>{item.demo ? 'Scenariusz demonstracyjny' : 'Źródło opublikowane'} · {item.evidenceLevel === 'concept' ? 'Opis koncepcji, bez oceny skuteczności' : item.evidenceLevel}</small><SourceFragments item={item} /></div><Button onClick={() => void createCard(item)}>Przygotuj Kartę wdrożenia <ArrowRight size={16} /></Button></article>)}</div>{result.innovations.length > 3 && !more && <Button secondary onClick={() => setMore(true)}>Pokaż pozostałe rozwiązania <ArrowDown size={17} /></Button>}
      {result.information.length > 0 && <section className="section-block"><h2>Wiedza, która pomaga zrozumieć sytuację</h2><div className="information-list">{result.information.map((item: any) => <div className="information-item" key={item.id}><span className="entry-icon sand"><BookOpen size={22} /></span><div><h3>{readableDemoTitle(item.title).title}</h3><DemoTitleDetails title={item.title} /><p>{item.summary}</p>{item.sources?.map((s: any) => <a key={s.id} href={s.url} target="_blank" rel="noreferrer">Otwórz źródło <ArrowUpRight size={13} /></a>)}<SourceFragments item={item} /></div></div>)}</div></section>}
      <section className="save-need panel"><div>{user && ['admin', 'operator'].includes(user.role) && <div className="stack"><Checkbox label="Pomagam innej osobie w zgłoszeniu" checked={assisted} onChange={setAssisted} />{assisted && <><Input label="E-mail konta autora potrzeby" type="email" value={authorEmail} onChange={setAuthorEmail} /><Notice>Treść będzie czekać na potwierdzenie autora w jego Moich sprawach. Twoje imię zostanie zapisane jako osoby pomagającej. Autor sam zdecyduje o obserwowaniu.</Notice></>}</div>}<h2>Zapisz potrzebę i obserwuj nowe rozwiązania</h2><p>Zapisz potrzebę i wróć do niej, kiedy pojawi się nowa wiedza.</p><Checkbox label="Chcę otrzymywać powiadomienia o istotnych nowych dopasowaniach do tej potrzeby" checked={watch} onChange={setWatch} /></div><div className="button-row"><Button onClick={() => void saveNeed()}>{saved ? 'Aktualizuj potrzebę' : 'Zapisz moją potrzebę'}</Button><Button secondary onClick={() => { if (requireAuth()) navigate('messages'); }}>Zapytaj ROPS</Button></div></section><details className="trace"><summary>Jak powstał ten wynik?</summary><p>Korpus: {result.trace.corpusVersion} · Reguły: {result.trace.ruleVersion} · Model: {result.trace.model} · Czas: {(result.trace.durationMs / 1000).toFixed(1)} s. Wynik dopasowania nie jest oceną prawdopodobieństwa powodzenia.</p></details>
    </section>}<Modal open={comparison} onClose={() => setComparison(false)} title="Porównanie rozwiązań"><div className="table-wrap"><table><thead><tr><th>Rozwiązanie</th><th>Warunki i bariery</th><th>Podstawa</th></tr></thead><tbody>{result?.innovations.filter((x: any) => compare.includes(x.id)).map((x: any) => <tr key={x.id}><th>{readableDemoTitle(x.title).title}<DemoTitleDetails title={x.title} /></th><td>{x.conditions.map((c: any) => <p key={c.id}>{c.label}: {c.status === 'met' ? 'spełniony' : c.status === 'unmet' ? 'niespełniony' : 'nieznany'}</p>)}</td><td>{x.demo ? 'Koncepcja demonstracyjna' : x.evidenceLevel}</td></tr>)}</tbody></table></div></Modal></>;
}
export function LibraryPage() {
  const { navigate } = useApp();
  const [search, setSearch] = useState(''); const [type, setType] = useState(''); const [theme, setTheme] = useState(''); const [map, setMap] = useState(false);
  const queryText = [search, theme].filter(Boolean).join(' '); const { results: items, status: pageStatus, loadMore } = usePaginatedQuery(endpoint.knowledge.page, { ...(queryText ? { search: queryText } : {}), ...(type ? { type } : {}) }, { initialNumItems: 24 });
  const filtered = (items || []).filter((k: any) => !theme || k.tags.includes(theme));
  const resultSummary = pageStatus === 'LoadingFirstPage' ? '' : filtered.length === 0
    ? 'Nie znaleziono materiałów. Zmień temat lub usuń część filtrów.'
    : `${filtered.length} wyświetlonych materiałów · aktualne, opublikowane wersje`;
  return <><PageHeading eyebrow="ZASOBNIK WIEDZY" title="Wybierz wiedzę do swojego projektu" description="Przeglądaj innowacje, raporty, filmy i kursy. Sprawdź źródła oraz warunki zastosowania." /><div className="library-toolbar panel"><div className="search-input"><Search size={19} /><input aria-label="Szukaj w bibliotece" placeholder="Szukaj po nazwie, potrzebie lub słowie…" value={search} onChange={e => setSearch(e.target.value)} /></div><Select label="Rodzaj materiału" value={type} onChange={setType} options={[{ value: '', label: 'Wszystkie materiały' }, { value: 'innovation', label: 'Innowacje' }, { value: 'report', label: 'Raporty i diagnozy' }, { value: 'course', label: 'Edukacja' }, { value: 'video', label: 'Filmy i transkrypcje' }, { value: 'case', label: 'Doświadczenia z testów' }]} /><button aria-pressed={map} className={`button secondary ${map ? 'selected' : ''}`} onClick={() => setMap(!map)}>{map ? <List size={18} /> : <MapPin size={18} />}{map ? 'Lista materiałów' : 'Mapa wyzwań'}</button></div><div className="filter-chips"><button className={!theme ? 'selected' : ''} onClick={() => setTheme('')}>Wszystkie tematy</button>{themes.map(t => <button className={theme === t.key ? 'selected' : ''} key={t.key} onClick={() => setTheme(t.key)}>{t.label}</button>)}</div>
    {map && <RegionalMap />}
    <div className="section-heading"><p id="library-results-status" className="muted" role="status" aria-live="polite" aria-atomic="true">{resultSummary}</p><span className="subtle"><SlidersHorizontal size={15} /> Kolejne materiały wczytujesz na żądanie</span></div>{pageStatus === 'LoadingFirstPage' ? <Loading /> : filtered.length === 0 ? <Empty title="Nie znaleźliśmy materiałów">Zmień temat lub usuń część filtrów.</Empty> : <div className="innovation-grid">{filtered.map((item: any, i: number) => { const readable = readableDemoTitle(item.title); return <article className="innovation-card" key={item._id}>{item.kind === 'innovation' && <button className="art-button" aria-label={`Otwórz ${readableDemoTitle(item.title).title}`} onClick={() => navigate('innovation', item._id)}><Artwork type={i} /></button>}<div className="innovation-body"><div className="card-meta"><Badge>{item.kind === 'innovation' ? 'Innowacja' : item.kind === 'report' ? 'Raport / przewodnik' : 'Materiał edukacyjny'}</Badge>{item.demo && <span className="subtle">Demo</span>}</div><h3><button onClick={() => navigate('innovation', item._id)}>{readable.title}</button></h3><DemoTitleDetails title={item.title} /><p>{item.summary}</p><button className="text-button" onClick={() => navigate('innovation', item._id)}>Zobacz materiał <ArrowRight size={17} /></button></div></article>; })}</div>}{pageStatus !== 'Exhausted' && pageStatus !== 'LoadingFirstPage' && <div className="section-block"><Button secondary loading={pageStatus === 'LoadingMore'} onClick={() => loadMore(24)}>Pokaż więcej materiałów <ArrowDown size={17} /></Button></div>}</>;
}
export function InnovationPage({ id }: { id: string }) {
  const item = useQuery(endpoint.knowledge.get, { id }); const save = useMutation(endpoint.hub.save); const { navigate, requireAuth, toast } = useApp();
  if (item === undefined) return <Loading />; if (!item) return <Empty title="Materiał jest niedostępny">Mógł zostać wycofany lub wymaga ponownego zatwierdzenia.</Empty>;
  async function create() { if (!requireAuth()) return; try { const needId = await save({ kind: 'need', title: `Zastosowanie: ${item.title}`, data: { description: `Chcemy zastosować rozwiązanie ${item.title} w naszej społeczności. ${item.summary}`, watch: false, group: item.audienceTags.join(', '), resources: {} } }); const cardId = await save({ kind: 'card', title: `${item.title}: plan wdrożenia`, data: { needId, innovationId: id, innovationVersion: item.version, sourceIds: item.sourceIds, goal: '', audience: item.audienceTags.join(', '), mechanism: item.summary, requirements: item.requirements, resources: {}, budgetItems: [], provenance: item.demo ? 'Źródło demonstracyjne' : 'Fakt źródłowy' } }); navigate('card', cardId); } catch (e) { toast(errorText(e), true); } }
  return <><button className="text-button back-link" onClick={() => navigate('library')}>← Wróć do biblioteki</button><PageHeading eyebrow="KARTA WIEDZY" title={readableDemoTitle(item.title).title} description={item.summary} action={<Badge>{item.demo ? 'Materiał demonstracyjny' : 'Źródło opublikowane'} · v{item.version}</Badge>} /><DemoTitleDetails title={item.title} /><div className="detail-layout"><article className="panel prose"><h2>Na czym polega rozwiązanie?</h2><p>{item.body}</p><h2>Co trzeba zapewnić?</h2>{item.requirements?.length ? item.requirements.map((r: any) => <div className="condition unknown" key={r.id}><span>?</span><div><strong>{r.label}</strong><small>{r.mandatory ? 'Warunek obowiązkowy' : 'Warunek zalecany'} · {r.allowPartner ? 'Może zapewnić potwierdzony partner' : 'Wymaga zasobu własnego'}</small></div></div>) : <p>Materiał informacyjny nie ustanawia warunków wdrożenia.</p>}{item.metadata?.videoUrl && <section className="video-learning"><h2>Film o rozwiązaniu</h2><video controls preload="metadata" style={{ width: '100%', borderRadius: 12 }} aria-label={item.title}><source src={item.metadata.videoUrl} type="video/mp4" />{item.metadata.vttUrl && <track kind="captions" src={item.metadata.vttUrl} srcLang="pl" label="Polski" default />}Twoja przeglądarka nie obsługuje wideo.</video><p>Transkrypcję i opis działań znajdziesz poniżej.</p></section>}{item.metadata?.steps?.length > 0 && <section><h2>Przejdź materiał krok po kroku</h2><ol className="process-flow">{item.metadata.steps.map((step: any, i: number) => <li key={i}><span>{i + 1}</span><div><h3>{typeof step === 'string' ? `Krok ${i + 1}` : step.title}</h3><p>{typeof step === 'string' ? step : step.body || step.description}</p></div></li>)}</ol></section>}{item.metadata?.transcript && <><h2>Transkrypcja materiału</h2><p>{item.metadata.transcript}</p></>}<h2>Źródła i podstawa rozwiązania</h2>{(item.sources || []).map((s: any) => <div className="source-detail" key={s._id}><a href={s.url} target="_blank" rel="noreferrer">{s.title} <ArrowUpRight size={16} /></a><p>{s.publisher} · {s.geography} · wersja {s.version}</p><small>{s.rights}</small></div>)}<Notice>{item.demo ? 'Autorska koncepcja demonstracyjna.' : `Poziom dowodów: ${item.evidenceLevel}.`}</Notice></article><aside className="panel side-summary"><span className="entry-icon mint"><Sprout size={25} /></span><h2>Zaplanuj zastosowanie u siebie</h2><p>Sprawdź warunki w swojej instytucji i przygotuj własną Kartę wdrożenia.</p>{item.kind === 'innovation' ? <Button onClick={() => void create()}>Przygotuj Kartę <ArrowRight size={17} /></Button> : <Button onClick={() => navigate('search')}>Opisz własną potrzebę <ArrowRight size={17} /></Button>}<Button secondary onClick={() => { if (requireAuth()) navigate('messages'); }}>Skonsultuj z ROPS</Button><div className="soft-note"><ShieldCheck size={20} /><p>Zmiany źródła nie nadpiszą zaakceptowanej wersji Twojej Karty.</p></div></aside></div></>;
}

function SourceFragments({ item }: { item: any }) {
  if (!item.fragments?.length) return null;
  return <details className="source-fragments"><summary>Fragmenty źródła ({item.fragments.length})</summary><p className="subtle">Sekcje opublikowanej wersji wykorzystane przy dopasowaniu.</p>{item.fragments.map((fragment: any) => <figure key={fragment.id}><figcaption><strong>{fragment.locator || 'Fragment dokumentu'}</strong> · wersja {fragment.version}{item.citedFragmentIds?.includes(fragment.id) && <Badge>Podstawa uzasadnienia</Badge>}</figcaption><blockquote>{String(fragment.text || '').slice(0, 1200)}{fragment.text?.length > 1200 ? '…' : ''}</blockquote></figure>)}</details>;
}
