import { useState } from 'react';
import { useMutation } from 'convex/react';
import { api } from '../convex/_generated/api';
import { ShieldCheck, Trash2 } from 'lucide-react';
import { useApp, isOperator } from './context';
import { Button, Input, Modal, Notice, PageHeading, errorText } from './ui';
import { LoginGate } from './Work';
export function SettingsPage() {
  const { user, toast, navigate } = useApp(); const erase = useMutation((api as any).privacy.eraseMyData); const [open, setOpen] = useState(false); const [confirmation, setConfirmation] = useState(''); const [busy, setBusy] = useState(false);
  if (!user) return <LoginGate />;
  return <><PageHeading eyebrow="TWOJE KONTO" title="Prywatność i ustawienia" description="Ty decydujesz o swoich zgłoszeniach i obserwowanych potrzebach." /><section className="panel stack"><h2>{user.name}</h2><p>{user.email}</p><Notice>Prywatne sprawy widzisz Ty, zaproszeni uczestnicy i uprawniony opiekun. Publiczna wiedza przechodzi osobną decyzję kuratora.</Notice><Button secondary onClick={() => navigate('cases')}>Ustaw obserwowanie i tryb ciszy</Button><Button secondary onClick={() => navigate('calls')}>Zarządzaj obserwowaniem naborów</Button><details><summary>Usuń własną przestrzeń roboczą</summary><div className="stack"><p>Usunięcie obejmuje prywatne rekordy, załączniki i pochodne dopasowania. Konto, opublikowana wiedza i minimalny ślad audytowy pozostają zachowane.</p>{isOperator(user) ? <Notice>Opiekun musi najpierw przekazać prowadzone sprawy innemu operatorowi. Samodzielne usunięcie przestrzeni operatora jest zablokowane.</Notice> : <Button secondary onClick={() => setOpen(true)}><Trash2 size={17} />Rozpocznij usuwanie danych</Button>}</div></details></section><Modal open={open} onClose={() => setOpen(false)} title="Potwierdź trwałe usunięcie swoich danych"><div className="stack"><Notice error>To działanie usuwa Twoją prywatną przestrzeń i nie może zostać cofnięte w aplikacji. Zapisz potrzebne eksporty przed kontynuacją.</Notice><Input label="Wpisz dokładnie: USUŃ MOJE DANE" value={confirmation} onChange={setConfirmation} /><Button disabled={confirmation !== 'USUŃ MOJE DANE'} loading={busy} onClick={async () => { setBusy(true); try { await erase({ confirmation }); for (const key of Object.keys(localStorage)) if (key.startsWith('splot:') && (key.includes(user.userId) || key === 'splot:search')) localStorage.removeItem(key); setOpen(false); toast('Przyjęto żądanie usunięcia. Czyszczenie prywatnej przestrzeni trwa w tle.'); } catch (error) { toast(errorText(error), true); } finally { setBusy(false); } }}>Usuń moje prywatne dane</Button></div></Modal></>;
}
