import { useEffect, useId, useRef, useState, type ReactNode, type ButtonHTMLAttributes } from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import { ArrowRight, Check, CircleAlert, LoaderCircle, X, FolderOpen } from 'lucide-react';

export type RecordItem = { _id: string; title: string; kind: string; status: string; version: number; ownerId: string; data: any; createdAt: number; updatedAt: number; history?: any[] };
export const labels: Record<string, string> = { awaiting_author: 'Czeka na potwierdzenie autora', draft: 'Szkic', review: 'Do weryfikacji', expert_review: 'Weryfikacja eksperta', submitted: 'Przekazano do ROPS', accepted: 'Przyjęto', approved: 'Zatwierdzono', indexing: 'Przygotowywanie publikacji', published: 'Opublikowano', withdrawn: 'Wycofano', rejected: 'Odrzucono', recruiting: 'Trwają zapisy', running: 'W trakcie testu', completed: 'Zakończono', reviewed: 'Wnioski zatwierdzone', proposed: 'Propozycja', open: 'Otwarty', closed: 'Zamknięty', pending: 'Oczekuje', invited: 'Zaproszenie', active: 'Aktywne', resolved: 'Rozwiązano', review_required: 'Wymaga przeglądu', blocked: 'Wstrzymano', institution: 'Instytucja', resident: 'Mieszkaniec', expert: 'Ekspert', admin: 'ROPS', administrator: 'ROPS', operator: 'Opiekun ROPS', curator: 'Kurator', rops: 'ROPS', innovation: 'Innowacja', report: 'Raport', education: 'Edukacja', video: 'Film', case: 'Doświadczenie', changes_requested: 'Prośba o uzupełnienie' };
export function Button({ children, secondary = false, small = false, loading = false, className = '', ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { secondary?: boolean; small?: boolean; loading?: boolean }) {
  return <button className={`button ${secondary ? 'secondary' : ''} ${small ? 'small' : ''} ${className}`} {...props} disabled={props.disabled || loading}>{loading && <LoaderCircle size={17} className="spin" />}{children}</button>;
}
export function Badge({ children, tone = '' }: { children: ReactNode; tone?: string }) { return <span className={`badge ${tone}`}>{children}</span>; }
export function Status({ value }: { value: string }) { return <Badge tone={['approved', 'published', 'accepted', 'running', 'active', 'reviewed'].includes(value) ? 'good' : ['rejected', 'withdrawn', 'blocked'].includes(value) ? 'danger' : ''}>{labels[value] || value}</Badge>; }
export function PageHeading({ eyebrow, title, description, action }: { eyebrow: string; title: string; description?: string; action?: ReactNode }) { return <div className="page-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1>{description && <p>{description}</p>}</div>{action}</div>; }
export function Field({ label, hint, error, children }: { label: string; hint?: string; error?: string; children: ReactNode }) { const id = useId(); return <div className="field"><label id={id}>{label}</label>{children}{hint && <small id={`${id}-hint`} className="field-hint">{hint}</small>}{error && <small role="alert" className="field-error">{error}</small>}</div>; }
export function Input({ label, value, onChange, type = 'text', placeholder, required, hint, origin, ...props }: { label: string; value?: any; onChange: (v: any) => void; type?: string; placeholder?: string; required?: boolean; hint?: string; origin?: string; min?: number; max?: number; step?: string; disabled?: boolean }) {
  const id = useId(); return <div className="field"><label htmlFor={id}>{label}{required && <span aria-hidden="true"> *</span>}</label><input id={id} aria-describedby={[hint && `${id}-hint`, origin && `${id}-origin`].filter(Boolean).join(" ") || undefined} type={type} value={value ?? ''} onChange={e => onChange(type === 'number' ? (e.target.value === '' ? '' : Number(e.target.value)) : e.target.value)} placeholder={placeholder} required={required} {...props} />{hint && <small id={`${id}-hint`} className="field-hint">{hint}</small>}{origin && <small id={`${id}-origin`} className="field-origin">{origin}</small>}</div>;
}
export function Textarea({ label, value, onChange, placeholder, rows = 4, required, hint, origin }: { label: string; value?: string; onChange: (v: string) => void; placeholder?: string; rows?: number; required?: boolean; hint?: string; origin?: string }) { const id = useId(); return <div className="field"><label htmlFor={id}>{label}{required && <span aria-hidden="true"> *</span>}</label><textarea id={id} aria-describedby={[hint && `${id}-hint`, origin && `${id}-origin`].filter(Boolean).join(" ") || undefined} value={value || ''} onChange={e => onChange(e.target.value)} placeholder={placeholder} rows={rows} required={required} />{hint && <small id={`${id}-hint`} className="field-hint">{hint}</small>}{origin && <small id={`${id}-origin`} className="field-origin">{origin}</small>}</div>; }
export function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (v: string) => void; options: { value: string; label: string }[] }) { const id = useId(); return <div className="field"><label htmlFor={id}>{label}</label><select id={id} value={value} onChange={e => onChange(e.target.value)}>{options.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</select></div>; }
export function Checkbox({ label, ariaLabel, checked, onChange }: { label: string; ariaLabel?: string; checked: boolean; onChange: (v: boolean) => void }) { return <label className="checkbox"><input type="checkbox" aria-label={ariaLabel} checked={checked} onChange={e => onChange(e.target.checked)} /><span>{label}</span></label>; }
export function Notice({ children, error = false }: { children: ReactNode; error?: boolean }) { return <div role={error ? 'alert' : 'status'} className={`notice ${error ? 'error' : ''}`}><CircleAlert size={19} /><div>{children}</div></div>; }
export function Empty({ title = 'Tu zaczyna się coś dobrego', children, action }: { title?: string; children?: ReactNode; action?: ReactNode }) { return <div className="empty"><FolderOpen size={34} /><h3>{title}</h3><p>{children}</p>{action}</div>; }
export function Loading() { return <div className="loading" role="status"><LoaderCircle className="spin" size={24} /> Ładowanie danych…</div>; }
export function Modal({ open, onClose, title, children, description }: { open: boolean; onClose: () => void; title: string; children: ReactNode; description?: string }) {
  const returnFocus = useRef<HTMLElement | null>(null);
  return <Dialog.Root open={open} onOpenChange={v => !v && onClose()}><Dialog.Portal><Dialog.Overlay className="modal-overlay" /><Dialog.Content className="modal-content" onOpenAutoFocus={() => {
    returnFocus.current = document.activeElement instanceof HTMLElement ? document.activeElement : null;
  }} onCloseAutoFocus={event => {
    event.preventDefault();
    const trigger = returnFocus.current;
    if (trigger?.isConnected && trigger !== document.body && !trigger.matches(':disabled') && !trigger.closest('[hidden], [inert]') && trigger.getClientRects().length) trigger.focus({ preventScroll: true });
    else document.getElementById('main-content')?.focus({ preventScroll: true });
  }}><div className="modal-heading"><Dialog.Title>{title}</Dialog.Title><Dialog.Close aria-label="Zamknij" className="icon-button"><X size={22} /></Dialog.Close></div><Dialog.Description className={description ? 'muted' : 'sr-only'}>{description || title}</Dialog.Description>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>;
}

export function Stepper({ steps, active = 0 }: { steps: string[]; active?: number }) { return <ol className="stepper">{steps.map((s, i) => <li key={s} className={i <= active ? 'done' : ''}><span>{i < active ? <Check size={14} /> : i + 1}</span>{s}{i < steps.length - 1 && <ArrowRight size={14} />}</li>)}</ol>; }
export function useDraft<T>(key: string, initial: T) { const [data, setData] = useState<T>(() => { try { const stored = localStorage.getItem(`splot:${key}`); return stored ? JSON.parse(stored) : initial; } catch { return initial; } }); useEffect(() => { localStorage.setItem(`splot:${key}`, JSON.stringify(data)); }, [key, data]); return [data, setData] as const; }
export function date(value?: number | string) { return value ? new Intl.DateTimeFormat('pl-PL', { dateStyle: 'medium', timeZone: 'Europe/Warsaw' }).format(new Date(value)) : 'Do ustalenia'; }
export function localDate(value: number = Date.now()) { return new Intl.DateTimeFormat('en-CA', { timeZone: 'Europe/Warsaw', year: 'numeric', month: '2-digit', day: '2-digit' }).format(value); }
export function warsawTime(day: string, time = '00:00:00') { if (!/^\d{4}-\d{2}-\d{2}$/.test(day)) return NaN; const assumed = new Date(`${day}T${time}Z`); const zone = new Intl.DateTimeFormat('en', { timeZone: 'Europe/Warsaw', timeZoneName: 'longOffset' }).formatToParts(assumed).find(part => part.type === 'timeZoneName')?.value.replace('GMT', '') || '+01:00'; return new Date(`${day}T${time}${zone}`).getTime(); }
export function money(grosz?: number) { return grosz === undefined || grosz === null ? 'Brak wyceny' : new Intl.NumberFormat('pl-PL', { style: 'currency', currency: 'PLN', maximumFractionDigits: 2 }).format(grosz / 100); }
export function exportJson(name: string, value: unknown) { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2)], { type: 'application/json' })); a.download = name; a.click(); URL.revokeObjectURL(a.href); }
export function exportCard(record: any, data: any, title: string, print = false) {
  const escape = (value: any) => String(value ?? 'Nie określono').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!));
  const fields = [['Cel', data.goal], ['Odbiorcy', data.audience], ['Mechanizm działania', data.mechanism], ['Adaptacje lokalne', data.adaptations], ['Działania, osoby i terminy', data.timeline], ['Dostępność', data.accessibility], ['Ryzyka', data.risks], ['Plan pomiaru', data.metrics], ['Wariant alternatywny', typeof data.alternatives === 'object' ? JSON.stringify(data.alternatives, null, 2) : data.alternatives]];
  const budget = data.budgetItems || [];
  const html = `<!doctype html><html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)} | Splot</title></head><body><main><p>SPLOT DLA HUBMI · DOKUMENT DEMONSTRACYJNY</p><h1>${escape(title)}</h1><p>Karta: ${escape(record._id)}. Wersja: ${record.version}. Stan: ${escape(labels[record.status] || record.status)}. Data eksportu: ${escape(date(Date.now()))}.</p><p>Potrzeba: ${escape(data.needId)}, wersja ${escape(data.needVersion)}. Innowacja: ${escape(data.innovationId)}, wersja ${escape(data.innovationVersion)}. Źródła: ${escape((data.sourceIds || []).join(', '))}.</p><p>Pochodzenie: ${escape(data.provenance || 'Lokalne pola są deklaracją instytucji; opis innowacji jest przypiętym faktem źródłowym. Podpowiedzi AI wymagają przeglądu.')} Dane i partnerstwa demonstracyjne nie potwierdzają skuteczności społecznej.</p>${fields.map(([label, value]) => `<section><h2>${label}</h2><p>${escape(value).replace(/\n/g, '<br>')}</p></section>`).join('')}<section><h2>Warunki i deklaracje zasobów</h2><ul>${(data.requirements || []).map((r: any) => `<li><strong>${escape(r.label)}</strong> (${r.mandatory ? 'obowiązkowy' : 'zalecany'}). Wymagana wartość: ${escape(r.expected)}. Deklaracja: ${escape(data.resources?.[r.key]?.value ?? 'nieznana')}. Podstawa: ${escape(data.resources?.[r.key]?.basis || 'brak potwierdzenia')}.</li>`).join('')}</ul></section><section><h2>Budżet</h2><table><caption>Kwoty w PLN</caption><thead><tr><th scope="col">Pozycja</th><th scope="col">Ilość</th><th scope="col">Stawka</th><th scope="col">Koszt</th></tr></thead><tbody>${budget.map((b: any) => `<tr><th scope="row">${escape(b.label)}</th><td>${escape(b.quantity)}</td><td>${escape(money(b.unitPriceGrosz))}</td><td>${escape(b.unitPriceGrosz == null ? 'Nie wyceniono' : money(b.quantity * b.unitPriceGrosz))}</td></tr>`).join('')}</tbody></table><p>Znane koszty: ${money(budget.reduce((sum: number, b: any) => sum + Number(b.quantity || 0) * Number(b.unitPriceGrosz || 0), 0))}. ${budget.some((b: any) => b.unitPriceGrosz == null) ? 'Kosztorys niepełny: nieznana cena nie jest zerem.' : ''}</p></section><section><h2>Przypięty opis źródłowy</h2><p>${escape(data.sourceSnapshot?.body || data.mechanism)}</p></section></main></body></html>`;
  if (print) { const popup = window.open('', '_blank'); if (popup) { popup.document.write(html); popup.document.close(); popup.focus(); popup.print(); } }
  else { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([html], { type: 'text/html;charset=utf-8' })); a.download = `splot-karta-${record._id}.html`; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 1000); }
}
export function errorText(error: unknown) {
  const fallback = 'Nie udało się wykonać działania. Szkic został zachowany. Spróbuj ponownie.';
  const controlled = error && typeof error === 'object' && 'name' in error && error.name === 'ConvexError' && 'data' in error && typeof error.data === 'string' ? error.data : undefined;
  const message = controlled ?? (error instanceof Error ? error.message : String(error));
  if (controlled === undefined && /Server Error|Internal Server Error/i.test(message)) return fallback;
  return message.replace(/^.*?Uncaught (?:ConvexError|Error):\s*/s, '').replace(/\s+at .*$/s, '').replace(/\[Request ID:[^\]]*\]/g, '').trim() || fallback;
}
